### ISSUE TITLE
edited system partition stays same

### ISSUE THREAD

**Issue by ghost** [natinusala/linux-amlogic-toolkit#5]
When I am repacking rom with edited system partition it packs the original system partition.

I get "./bin/repack: line 9: bin/recreate: Permission denied" when repacking. I also get permission denied when I try "./bin/flash".

I solved it. The problem was that flash.sh and recreate.sh had unchecked "is executable".

**Comment by iamfilipc** [comment]
My guess is that I need those i386 packages. I might have uninstalled them accidently because repacking worked for me a week ago. Can someone please tell me wchich I need for arch linux?
